# Generated by Django 4.0.4 on 2022-06-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_app', '0002_supplyclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentClass',
            fields=[
                ('equipment_class', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('billing_code', models.CharField(max_length=20)),
                ('rates', models.PositiveIntegerField(blank=True)),
                ('active', models.CharField(choices=[('Y', 'Active'), ('N', 'Inactive')], default='Y', max_length=1)),
            ],
            options={
                'db_table': 'EquipmentCode',
            },
        ),
    ]
